### ISSUE TITLE
web installer: allow to load system image locally

### ISSUE THREAD

**Issue by secretmango** [GrapheneOS/grapheneos.org#1068]
Not sure if this is the right issuetracker

For airgapped factory reset / overwrite, using a secondary phone, with a somewhat recent OS image on it, and the webinstaller, would be really good.

Flashing a local image without internet is currently only available on a PC.

Adding a button to load a local image file alternatively would be really useful here.

**Comment by thestinger** [comment]
This could be done elsewhere but doesn't really belong in the web installer on the website since you have to load that from the website. There could be an offline variant of the web installer but that can't really be on the site.

You can already download an image and use it later via the cache for the web installer.
