### ISSUE TITLE
Confusing `fastboot` version number

### ISSUE THREAD

**Issue by fwdekker** [GrapheneOS/grapheneos.org#11]
The [installation page](https://grapheneos.org/install) states that the `fastboot` tool must be at least version `28.0.0`, and notes that this can be checked by running `fastboot --version`. However, on Ubuntu, running `fastboot --version` prints the following:
```
fastboot version 1:8.1.0+r23-5~18.04
Installed as /usr/lib/android-sdk/platform-tools/fastboot
```
It is not immediately obvious how this version number compares with version `28.0.0`. As such, the page should be updated to include instructions on how to check the version number.

**Comment by thestinger** [comment]
> As such, the page should be updated to include instructions on how to check the version number.

It does include instructions on how to check the version number via `fastboot --version`.

Here's an example with the current stable release of the SDK:

```
% fastboot --version
fastboot version 29.0.1-5644136
Installed as /home/strcat/sdk/platform-tools/fastboot
```

Here's another example with the version in the GrapheneOS source tree (`pie` branch):

```
$ fastboot --version
fastboot version 28.0.0 rc1-2019.06.17.05
Installed as /home/strcat/android/grapheneos/out/host/linux-x86/bin/fastboot
```

The version you're showing above is not in the native fastboot version format. Your Linux distribution is defining their own versioning scheme which appears to be based on Android Open Source Project tags. They are probably referring to the `android-8.1.0_r23` tag, but this is not the versioning scheme used for `fastboot`. They've also added a prefix (likely their package epoch, `1:`) and suffix (`-5~18.04`, which may represent the package release number within a branch for the OS version). I'm not able to work around Linux distributions defining their own versioning schemes. I don't think they should be overriding the standard version completely rather than only appending to it.

**Comment by thestinger** [comment]
A normal fastboot version is the platform-tools version, which is based on the API level. The native API level for Android 9 is 28, which is why the version for Android 9 started from `28.0.0`. Linux distributions should not be completely changing the versioning scheme. It should be reported as an issue to them, as I don't maintain their packages and can't support ad-hoc overrides of the standard versioning scheme specific to Linux distributions. Their package is definitely at least a year too old, and who knows what kind of downstream changes they've made to it. Distribution packages cannot be relied upon unless they are going to ship an up-to-date stable release with the standard versioning scheme and without questionable downstream changes.

**Comment by fwdekker** [comment]
Thank you for the extensive response! You're right, it's not sensible to expect the instructions to explain every version scheme of every random distributor. It would be great if my source used a different version scheme, but I guess that's that. Thank you!
