### ISSUE TITLE
E-mail app deleted after update.

### ISSUE THREAD

**Issue by alllof** [GrapheneOS/grapheneos.org#132]
Mi,
the update process deleted FairEmail app from my device and cannot be installed again from F-Froid repository.
Unknown error during installation process.

All this since the latest update.
RP1A.200720.009.2020.09.25.00

**Comment by thestinger** [comment]
F-Droid has broken builds of apps where they are using legacy pre-2016 v1 signatures which are forbidden with targetSdkVersion 30+.

**Comment by thestinger** [comment]
https://developer.android.com/about/versions/11/behavior-changes-11#minimum-signature-scheme

**Comment by thestinger** [comment]
v2 signatures were released as a security update to the signature format as part of the release of Android 7 in 2016. They were supported by the SDK before Android 7 was available to test on the previews and betas. It has been over 4 years since this has been available. Also, nothing breaks unless an apk claims to target API 30+ but still has a v1 signature. This is the fault of F-Droid, not the app developers, since it is only an issue with the F-Droid builds of the apps. AOSP did not expect anyone to be using broken apks with API 30+ with v1 signatures. It disables the broken apps when it boots up and finds them. You'll need to wait until F-Droid fixes the remaining apps. They finally started dealing with it once this happened.
