### ISSUE TITLE
Graphene OS Location Problems

### ISSUE THREAD

**Issue by michael1999crypto** [GrapheneOS/grapheneos.org#141]
Hello folks,

sorry if I bother you.

I basically own a Google Pixel 3 and yesterday I flashed my phone with GrapheneOS.

I know that this operating system comes with some limitations, 

but I do have a problem with location services. I basically use the app "112-where are you?" which is an app that shares your current position with emergency services in Italy.

Can you please edit the code, so that some apps have access to location services, no matter what?

The above mentioned e.g. is very important when I should require emergency services.

Please see Screenshotvideo: [https://youtu.be/Jzv9luzHtqg](url)

**Comment by thestinger** [comment]
> I know that this operating system comes with some limitations,

We don't break any functionality like this. GrapheneOS doesn't have limitations on functionality compared to AOSP.

> Can you please edit the code, so that some apps have access to location services, no matter what?

We don't restrict how location services work. If you allow the app access to location in the background, it has access to location in the background. It sounds like the app doesn't work properly without Google Play services. You should report that to the app developers rather than to us.

**Comment by thestinger** [comment]
Also, this is the issue tracker for the https://grapheneos.org/ website, not the OS. I'll transfer it.
