### ISSUE TITLE
signature verification failed

### ISSUE THREAD

**Issue by JudicialDomicide** [GrapheneOS/grapheneos.org#184]
I'm not familiar with Signify but I tried the following to verify if the .zip factory image signature matched.

`signify -V -x sargo-factory-2021.02.07.17.zip.sig -p factory.pub -m sargo-factory-2021.02.07.17.zip`

The output I get back is:
`signify: signature verification failed`

I also tried the short form as .sig is in the same directory as the .zip

`signify -V -p factory.pub –m sergo-factory-2021.02.07.17.zip`

The output I get back is:
`signify: signature verification failed`

However following the CLI guide command:

`signify -Cqp factory.pub -x sargo-factory-2021.02.07.17.zip.sig && echo verified`

works and output 
`verified`

but it looks like from the command that is just checking the signature file against the public key and not the factory image but I could be totally wrong. I have never used signify before only GPG. I consulted the https://man.openbsd.org/signify.1 manual and would assume that the above verifications should work to prove they were signed?

I am unsure of what I am doing wrong.

**Comment by JudicialDomicide** [comment]
I have manually verified that the sha256 checksum of the .zip image is a match from the details stated in the .sig file. 
This is good enough for me. I am just interested to understand why the above signature verification commands are failing.

**Comment by thestinger** [comment]
The signify command has first class support for BSD checksum files. You can remove the `-q` switch from the command we provide in order to see the whole output. This is the explanation of `-C`:

```
Verify a signed checksum list, and then verify the checksum for each file. If no files are specified, all of them are checked. sigfile should be the signed output of sha256(1).
```

```
% signify -Cp factory.pub -x sargo-factory-2021.02.07.17.zip.sig
Signature Verified
sargo-factory-2021.02.07.17.zip: OK
```

The reason that we use `-q` combined with `&& echo verified` to use the exit status is because this kind of output would be confusing:

```
% signify -Cp factory.pub -x sargo-factory-2021.02.07.17.zip.sig
Signature Verified
sargo-factory-2021.02.07.17.zip: FAIL
```

**Comment by JudicialDomicide** [comment]
Thanks but I'm still unclear. Why does the verify command not work as per my example? 

I understand that you are trying to simpify the output for the end user, but your command option is verifying the .sig derived from the public key and then a checksum validation on the sig file and the image .zip as opposed to a SIGNED image .zip? 
Is that correct? If you were signing the .zip file then the above commands would surely pass?

**Comment by thestinger** [comment]
Why would the verify command work? It's the checksum file that's signed, and the file is included in the checksum file. The `-C` command is the correct way to verify the signature of a checksum file and all files referenced in it via the hashes. It's not the zip that's signed directly but rather a hash of the zip is signed, and signify has first class support for doing it this way via the `-C` switch.

Signify isn't really meant to be used to sign a large file directly. It would take a really long time and memory equal to the size of the file to sign and verify. Instead, it uses a signed checksum file which you verify with `-C` to verify the checksum file with signify and the listed files with the hashes. It's just how signify works. If we used minisign with the minisign-specific signature format instead of signify, it would work the way you expect. Signify doesn't do any implicit pre-hashing but rather requires that you do it this way. See https://www.openbsd.org/faq/faq4.html#Download for how it's used by OpenBSD. It's the same thing, but they actually have multiple files.

**Comment by JudicialDomicide** [comment]
Thanks very much for the explanation. That makes sense.

**Comment by thestinger** [comment]
If we used https://github.com/jedisct1/minisign rather than the standard signify we could use the pre-hashing extension via `-H`. It wouldn't be possible to verify those signatures with signify. The reason we didn't do that is that Debian doesn't have a minisign package. If I only had to support Arch Linux, I'd happily have used minisign with `-H`.

It would be nice if signify supported this but we couldn't use it due to Debian having ancient versions of applications.

It's actually possible to sign and verify files with SSH so perhaps we should be doing that instead for more portability.

**Comment by JudicialDomicide** [comment]
Well I was on MacOS and already using homebrew. If you get time it would be great if the CLI installation guide could be updated for MacOS users already using homebrew.

`brew install signify-osx`

and then run your `signify -Cqp ***`

**Comment by JudicialDomicide** [comment]
For MacOS users: see https://github.com/jpouellet/signify-osx

If you prefer MacPorts:

`sudo port install signify`

If you prefer Homebrew:

`brew install signify-osx`

**Comment by thestinger** [comment]
Can you check the output of `ssh-keygen --help` with the OpenSSH that comes with macOS rather than a package manager version of it?

**Comment by thestinger** [comment]
We could be using `ssh-keygen` to do signing and verification instead of signify.

**Comment by JudicialDomicide** [comment]
Hi,

`ssh-keygen --help`

Gives the following output:
```
ssh-keygen: illegal option -- -
usage: ssh-keygen [-q] [-b bits] [-t dsa | ecdsa | ed25519 | rsa]
                  [-N new_passphrase] [-C comment] [-f output_keyfile]
       ssh-keygen -p [-P old_passphrase] [-N new_passphrase] [-f keyfile]
       ssh-keygen -i [-m key_format] [-f input_keyfile]
       ssh-keygen -e [-m key_format] [-f input_keyfile]
       ssh-keygen -y [-f input_keyfile]
       ssh-keygen -c [-P passphrase] [-C comment] [-f keyfile]
       ssh-keygen -l [-v] [-E fingerprint_hash] [-f input_keyfile]
       ssh-keygen -B [-f input_keyfile]
       ssh-keygen -D pkcs11
       ssh-keygen -F hostname [-f known_hosts_file] [-l]
       ssh-keygen -H [-f known_hosts_file]
       ssh-keygen -R hostname [-f known_hosts_file]
       ssh-keygen -r hostname [-f input_keyfile] [-g]
       ssh-keygen -G output_file [-v] [-b bits] [-M memory] [-S start_point]
       ssh-keygen -T output_file -f input_file [-v] [-a rounds] [-J num_lines]
                  [-j start_line] [-K checkpt] [-W generator]
       ssh-keygen -s ca_key -I certificate_identity [-h] [-U]
                  [-D pkcs11_provider] [-n principals] [-O option]
                  [-V validity_interval] [-z serial_number] file ...
       ssh-keygen -L [-f input_keyfile]
       ssh-keygen -A
       ssh-keygen -k -f krl_file [-u] [-s ca_public] [-z version_number]
                  file ...
       ssh-keygen -Q -f krl_file file ...
```

The above output is from MacOS Mojave 10.14.6 running all latest security patches.

**Comment by thestinger** [comment]
Looks like it isn't new enough to use it for verification of signatures.

**Comment by JudicialDomicide** [comment]
ssh-keygen --help

Gives the following output:
```
ssh-keygen: illegal option -- -
usage: ssh-keygen [-q] [-b bits] [-C comment] [-f output_keyfile] [-m format]
                  [-N new_passphrase] [-t dsa | ecdsa | ed25519 | rsa]
       ssh-keygen -p [-f keyfile] [-m format] [-N new_passphrase]
                   [-P old_passphrase]
       ssh-keygen -i [-f input_keyfile] [-m key_format]
       ssh-keygen -e [-f input_keyfile] [-m key_format]
       ssh-keygen -y [-f input_keyfile]
       ssh-keygen -c [-C comment] [-f keyfile] [-P passphrase]
       ssh-keygen -l [-v] [-E fingerprint_hash] [-f input_keyfile]
       ssh-keygen -B [-f input_keyfile]
       ssh-keygen -D pkcs11
       ssh-keygen -F hostname [-lv] [-f known_hosts_file]
       ssh-keygen -H [-f known_hosts_file]
       ssh-keygen -R hostname [-f known_hosts_file]
       ssh-keygen -r hostname [-g] [-f input_keyfile]
       ssh-keygen -G output_file [-v] [-b bits] [-M memory] [-S start_point]
       ssh-keygen -f input_file -T output_file [-v] [-a rounds] [-J num_lines]
                  [-j start_line] [-K checkpt] [-W generator]
       ssh-keygen -I certificate_identity -s ca_key [-hU] [-D pkcs11_provider]
                  [-n principals] [-O option] [-V validity_interval]
                  [-z serial_number] file ...
       ssh-keygen -L [-f input_keyfile]
       ssh-keygen -A [-f prefix_path]
       ssh-keygen -k -f krl_file [-u] [-s ca_public] [-z version_number]
                  file ...
       ssh-keygen -Q -f krl_file file ...
       ssh-keygen -Y check-novalidate -n namespace -s signature_file
       ssh-keygen -Y sign -f key_file -n namespace file ...
       ssh-keygen -Y verify -f allowed_signers_file -I signer_identity
       		-n namespace -s signature_file [-r revocation_file]
```
The above output is from MacOS Catalina 10.15.6 running all latest security patches.

**Comment by thestinger** [comment]
Ah, so it's new enough there.

**Comment by JudicialDomicide** [comment]
Happy to test the SSH method of validation if it would help?

**Comment by thestinger** [comment]
I need to figure out if it makes sense. It probably does because Windows also likely has OpenSSH available now as first party software.

**Comment by JudicialDomicide** [comment]
OpenSSH has been included in Windows since Late 2018. I think. Certainly in Windows 10.  
I think OpenSSH verification would be more familiar to people who already use SSH Keys and/or have used GPG Keys. Also as you rightly point out it would be better all round from a portability perspective.
