### ISSUE TITLE
Have links to community made wikis / sources

### ISSUE THREAD

**Issue by Shepherd115** [GrapheneOS/grapheneos.org#268]

**Comment by louipc** [comment]
Any examples?

**Comment by louipc** [comment]
Found one ;) https://shepherd115.github.io/Jep/

**Comment by ghost** [comment]
This one is good, by @Peter-Easton. A lot of it still applies, just needs a few updates.

https://github.com/Peter-Easton/GrapheneOS-Knowledge/

**Comment by Shepherd115** [comment]
So the idea was that people in the Matrix rooms often gets directed to sites like Madaidans insecurities, Peter Eastons Knowledge or https://hub.libranet.de/wiki/graphene-os/wiki/Home  so why not have a simple list of links to those in Contact -> Community part of the GrapheneOS website. I dont know if that is something that you would want but just an idea.

**Comment by Peter-Easton** [comment]
Some of my stuff in my old GrapheneOS-Knowledge notes desperately needs to be updated since some of was written for the days of Android 9 and that was a very long time ago now (yikes!). I'll try to see if I can get around to that when I have a bit more time, although by and far I will likely be trying to refer people to the authoritative documentation on the FAQ or User Guide or source from it instead.

**Comment by Lelmister101** [comment]
Sounds like a cool idea, but including a link might imply endorsement, so the sources should likely be vetted.

**Comment by Shepherd115** [comment]
Yeah that is true. Maybe only few sites could be there.  Also there could be small warning sign saying that they are not responsible for what is written in them @Lelmister101

**Comment by Lelmister101** [comment]
@Shepherd115 I agree with that, probably a combination of a warning and a few standards (regularly updated, proper representation of GrapheneOS, well sourced, etc.).

**Comment by thestinger** [comment]
Not planned.
