### ISSUE TITLE
Please continue supporting those "old" pixel phones (not that old)

### ISSUE THREAD

**Issue by equwal** [GrapheneOS/grapheneos.org#305]
These old phones are very usable. They are being sold by some sellers at very decent profits. *People want these*. They are very modern. They should be supported.

**Comment by equwal** [comment]
I see the problem is google's non-support for firmware updates. It is a shame that we are beholden to this decision of theirs; stuck using their proprietary firmware.

**Comment by thestinger** [comment]
> These old phones are very usable.

4GB of memory isn't that much due to GrapheneOS enabling the hardened_malloc slab quarantine feature along with using a secure spawning system.

> They are very modern.

No, not really, and they don't meet the current security requirements.

> I see the problem is google's non-support for firmware updates

Google wasn't the SoC vendor before the Pixel 6 and Pixel 6 Pro which have a guarantee of at least 5 years of support including security updates rather than a minimum of 3 years.

> It is a shame that we are beholden to this decision of theirs; stuck using their proprietary firmware.

It's irrelevant which parts of the firmware are open source. It has signature protection and also downgrade protection (although downgrade protection wasn't used much in the past despite being supported).

**Comment by thestinger** [comment]
5 years of support is long enough for the vast majority of people to not need further updates. There will be little reason to buy anything older than the Pixel 6 or Pixel 6 Pro since the value is so much better. Pixel 6 is extremely competitively priced for high-end flagship hardware. It costs $599 and is nicer hardware than phones costing more than $1000. I don't think there's much to complain about.

$599 is $119.8/year over the 5 years of minimum guaranteed support. The Pixel 5a cost $449 new which was $150.67/year over the 3 years of minimum guaranteed support.

**Comment by ghost** [comment]
No one's stopping you from using these devices. However, we can't support or call these devices secure when the vendor has dropped support. That goes against the point of a security focused OS.

These devices are not really "modern". Pixel 3 doesn't have 5G, only 4GB LPDDR4x of memory which makes a lot of GrapheneOS's hardening very tight, camera is only 12.2 MP, doesn't support WPA3 or Wi-Fi 6, USB Power Delivery 2.0, SSD is only UFS 2.1, and the max battery is only ~2915mAh.

Pixel 6 has 8GB LPDDR5 memory, UFS 3.1 SSD, ~4500mAh battery, USB PD 3.0, supports modern WPA3 and Wi-Fi 6, Bluetooth 5.2, and 50 MP camera. Among other typical higher end GPU, CPU, screen, neural core, etc

Both generations of devices are very usable, but it's not as modern as you think and we can't consider the device secure once official vendor support is gone.
