### ISSUE TITLE
FAQ section about privacy policy is missing

### ISSUE THREAD

**Issue by salim-b** [GrapheneOS/grapheneos.org#326]
In the [FAQ ToC](https://grapheneos.org/faq#table-of-contents) there's as entry *What is the privacy policy for GrapheneOS services?* (linking to the anchor `#privacy-policy`) but the the actual section is missing from the page.

I guess you meant to add a text similar to the one on [attestation.app/privacy-policy](https://attestation.app/privacy-policy)...

**Comment by thestinger** [comment]
The text is right there. You're using a content filter blocking content on the page in a section with the id `privacy-policy`, probably because that id is commonly used for cookie warnings. When you're using content filtering, you need to be aware that there are going to be a lot of false positives.

**Comment by thestinger** [comment]
Our section ids are chosen to make sense to humans and we even do special client-side redirects with JavaScript to preserve links to them after they get renamed or moved. Not going to be using a different name than `privacy-policy` just because misguided ad blockers decided to filter out that content. Should be reported to them as a very misguided and broken approach.

**Comment by salim-b** [comment]
Damnit, you're absolutely right.

> Our section ids are chosen to make sense to humans (...) Not going to be using a different name than `privacy-policy` just because misguided ad blockers decided to filter out that content.

Sure, sounds reasonable to me.

> Should be reported to them (...)

I've submitted a PR to EasyList, should get merged soon: https://github.com/easylist/easylist/pull/10310

> (...) as a very misguided and broken approach.

Yeah, I know the identifier-based cat-and-mouse-style blocking is far from being precise or sustainable. I'm relying on it mostly for convenience (being less distracted by the abundance of commercial BS on the web). Once in a while, it bites me, especially the cosmetic filtering (which I know doesn't provide any privacy benefits at all).
