### ISSUE TITLE
Missing signify signatures for sandboxed Google Play APKs?

### ISSUE THREAD

**Issue by crtxcr** [GrapheneOS/grapheneos.org#334]
The usage guide documents the availability of sandboxed Google Play: https://grapheneos.org/usage#sandboxed-google-play

It links to https://apps.grapheneos.org/packages/. There, the necessary APKs can be obtained.

In contrast to the GrapheneOS release, there are no signify or other signatures to verify the authenticity of the APKs.  

Does GrapheneOS have other means to detect malicious Google play APKs?

If not, in the the absence of signatures, users who want to use the sandboxed google play services have no choice but to trust that the download location mentioned above has not been compromised.

**Comment by thestinger** [comment]
That's not accurate. APK packages are signed. It's not possible to install an APK without a valid signature. It's mandatory for every app and there is no way to install or upgrade an APK without it. Once they're installed, the OS package manager enforces key pinning (with key rotation support) and downgrade protection itself.

Our app repository bootstraps the package signing used by APKs via the signed metadata. The metadata file used by our app repository client is signed and contains hashes of the APKs. You can see that there's a metadata.json with an indexed signature to support key rotation. Our usage guide section is very clear that manually installing them is a temporary approach until the app repository client is shipped.

**Comment by thestinger** [comment]
Only the GrapheneOS factory images are signed with signify signatures because the format doesn't have an internal signature. Our updates don't use signify signatures because the update zips have internal signing and enforced downgrade protection like APKs. The only use of the signify signatures is to bootstrap trust from another operating system for the factory images. It doesn't make much sense to use them unless your OS provides signify. If you obtained signify elsewhere, you'd just be running unverified software with full access to everything due to the lack of any meaningful application sandboxing on traditional operating systems. It would be making things worse, not better.

**Comment by crtxcr** [comment]
Thanks for the quick reply! My problem was actually the bootstrapping, perhaps should have been clearer. Anyway, thanks for pointing me to the metadata.json, I was now able to verify the APKs using it and corresponding signify keys.
