### ISSUE TITLE
Switch to BTCPay Server 

### ISSUE THREAD

**Issue by elkimek** [GrapheneOS/grapheneos.org#38]
Hi.

I'd like to propose BTCPay Server for donation purposes instead of static donation address. Address reuse is terrible from privacy perspective.

See: https://en.bitcoin.it/wiki/Address_reuse and https://www.ministryofnodes.com.au/2019/12/14/bitcoin-static-donation-addresses-suck/

BTCPay Server is self-hosted, open-source, self-validating gateway. No private keys are stored on the server. It's highly appreciated project in Bitcoin community, focused on privacy and security of its users.

See: https://btcpayserver.org/

BTCPay Server offers much more, it's Tor v3, Native SegWit (bc1q address type with much lower fees) and Lightning Network enabled.

There is also an option for crowfunding app. For example see [The Tor Project Crowfunding](https://bitcoinfortor.torproject.net/) 

I think BTCPay Server fits GrapheneOS ethos and the project could expect much more support with BTCPay Server enabled donations. GrapheneOS is highly recommended by well-listened Bitcoiners and cypherpunks like [Jameson Lopp](https://blog.lopp.net/grapheneos-phone-privacy-protection/) or the [Samourai Wallet](https://samouraiwallet.com/) project.

**Comment by renlord** [comment]
This is a really bad idea at this point in time. This adds more maintanence overhead on top of things waiting to be done.

**Comment by elkimek** [comment]
It's possible to use "shared" instance where you still own your private keys and don't maintain the whole thing. There are trade-offs but still better than reusing static address.

https://docs.btcpayserver.org/deployment/thirdpartyhosting

**Comment by elkimek** [comment]
Another and easier option would be to set-up a PayNym in mentioned Samourai Wallet. 

See: https://samouraiwallet.com/paynym && https://paynym.is/

**Comment by thestinger** [comment]
Using a static donation address adds zero maintenance, zero attack surface and gives me peace of mind that there won't be loss of funds from a compromise or software bug. I did some research into BTCPay and it looks like too much effort to set up and maintain. It also doesn't look like it'd work directly with an xpub from a Trezor since wallets wouldn't find all the funds past the gap limit.

Someone can bypass the privacy of avoiding address reuse by making donations and keeping an eye on them since they'll see when they get moved together with other donations.

https://en.bitcoin.it/wiki/Mystery_shopper_payments

I'm not really interested in a bunch of complexity / effort without clear benefits. I can't afford to invest the time in setting this up, maintaining it and managing the funds in another way, especially without any robust privacy benefits from it.

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/grapheneos.org/issues/91 is the current plan but it's a low priority.
