### ISSUE TITLE
Proposal: Way for users to contribute to documentation (wiki/forum/etc)

### ISSUE THREAD

**Issue by ddevz** [GrapheneOS/grapheneos.org#437]
Day 1 with GrapheneOS  :)

First, thanks for writing GrapheneOS, from what I read it sounds impressive and I'm pretty excited.

While the documentation for using GrapheneOS at https://grapheneos.org/usage is helpful, it seems like there could be a lot more.
However documentation takes time, and developer time is well spent developing.

Is there a way that a new user can log the solutions to the problems that he encounters for the next person?
If not perhaps add a wiki?

Or are users expected to just add things and then give pull requests for https://github.com/GrapheneOS/grapheneos.org ?

There is also a reddit group, but that seems to mainly be a news feed: https://www.reddit.com/r/GrapheneOS/search/?q=-released

**Comment by thestinger** [comment]
You should join the main 2 Matrix rooms:

#grapheneos:grapheneos.org
#offtopic:grapheneos.org

You can search those.

https://grapheneos.org/contact#community

**Comment by ddevz** [comment]
Searching the log there seems to be difficult.  Some questions are asked every few hours, and therefore they don't normally get answered very comprehensively.  (presumably they were answered the first time at least once in the stack).

If I started writing some documentation for users based on my interpretations of what I can find through searching (google and matrix), would people be willing to correct my wrong assumptions so we could add it to the site?

( documentation could be done as a pull request for https://github.com/GrapheneOS/grapheneos.org)

**Comment by thestinger** [comment]
If there are issues with a pull request adding new documentation, it's not going to be merged. Most pull requests for the web site aren't merged. It's not practical to get someone to improve documentation to meet our requirements / standards based on review and is a poor use of time. It's faster to write it ourselves. We have a lot of documentation already and we don't have unlimited time to make more. We don't have time to moderate / manage a wiki especially due to the ongoing and escalating attacks / abusive behavior towards our project/developers. We cannot add more platforms we have to moderate.

**Comment by ddevz** [comment]
Ok, was trying to help.
