### ISSUE TITLE
Document Privacy Considerations For Google Services

### ISSUE THREAD

**Issue by seniorm0ment** [GrapheneOS/grapheneos.org#468]
After reading the entire page on Google Services, I still am left with a handful of questions which I think would benefit from having a section to explain them on the website for users.

The questions imply the user is using google services on the owner profile, instead of an isolated profile, which means all apps are installed under one profile with google services enabled:

- What exactly is the differences between sandboxed google services, compared to a grapheneos device without any google services, compared to a regular device with google services (and maybe a 4th compared to microg on something like lineageos) - the privacy impacts, concerns, and considerations.

- If one chooses to enable google services on grapheneos, what information is sent to Google? what are the privacy considerstions and concerns? 

- Are there any protections in place to minimize the amount of data being sent to google when enabled?

- does it only affect apps that use google services? for example Snapchat versus a complete libre app? will google be able to gather information about all my libre apps, or just the ones that rely on google services is my question? 

- how does the location rerouting work, what are the pros and cons of it being on or off? if relocating is on, does it not send any location data to google? (obviously the apps using location will still gather this info)

**Comment by thestinger** [comment]
> After reading the entire page on Google Services, I still am left with a handful of questions which I think would benefit from having a section to explain them on the website for users.

Our documentation explains that GrapheneOS does not include Google Play or other Google services and the OS doesn't use it if you install it. It explains that Google Play installed on GrapheneOS are simply a set of regular apps without any special access or privileges. That answers all the questions.

If you need further clarification, please ask these questions on the discussion forum or the main Matrix chat room. We can't take requests for new documentation based on questions.

> What exactly is the differences between sandboxed google services, compared to a grapheneos device without any google services, compared to a regular device with google services (and maybe a 4th compared to microg on something like lineageos) - the privacy impacts, concerns, and considerations.

They're regular apps in the full standard app sandbox. No difference from other regular apps. No special concerns. Same permission model, access control and choices as with any other app. I think we already do a sufficient job explaining that they are fully sandboxed regular apps as opposed to deeply privileged OS components with immense access and control over the device. There are not many limits to what Google Play can do on the stock OS or elsewhere with regular Google Play integration.

microG is an insecure mess providing a tiny subset of Google Play services. It's unlikely to be covered by our documentation. It has nowhere close to viable app compatibility for the majority of users, requires privileged access to function, runs Google binaries (snet, droidguard) within the same privileged context and has insecure implementations of many of the APIs where apps can leak data from other apps or bypass parts of the permission model such as not all of the AppOps-based restrictions being implemented. It has never been supported by GrapheneOS or by LineageOS. It's very niche software and wasn't ever considered as an option due to the serious security issues paired with lack of broad app compatibility including not having any of the Play Store services and missing 80% of Play services APIs.

> If one chooses to enable google services on grapheneos, what information is sent to Google? what are the privacy considerstions and concerns?

As above, they're regular sandboxed apps without special access. There are no special concerns about what they can access. If an app chooses to use Google services, they can do that without Google Play being installed. Install and try Google Maps without sandboxed Google Play and you can see that using Google services in no way requires Google Play services. Having sandboxed Google Play gives exactly zero additional access or capabilities to Google's code included in the apps using their libraries/services. The answer is it provides zero additional access.

> Are there any protections in place to minimize the amount of data being sent to google when enabled?

That's the whole point, they're fully sandboxed regular apps. There's no difference from what we do for other apps. It is not a special sandbox, it is the full standard API 32 app sandbox.

> does it only affect apps that use google services? for example Snapchat versus a complete libre app? will google be able to gather information about all my libre apps, or just the ones that rely on google services is my question?

They're all fully sandboxed regular apps. No difference beyond some apps like Google Play targeting the latest API 32 and others targeting older API levels. Each new target API level slightly improves the app sandbox. Most of the privacy and security improvements in new major Android releases are enforced for all apps, but some are too backwards compatible and are applied based on API level. In some cases that means apps below a certain API level get a special access grant by default instead of needing to receive it from the user. Google Play mandates that apps target API 30 or above for both new apps and updates to existing apps. GrapheneOS displays a warning for API below 28. Google Play apps themselves always target the latest API level, so with sandboxed Google Play on GrapheneOS it's the strongest, most restricted available app sandbox provided by the OS.

https://developer.android.com/google/play/requirements/target-sdk

> how does the location rerouting work, what are the pros and cons of it being on or off? if relocating is on, does it not send any location data to google? (obviously the apps using location will still gather this info)

They're regular apps in the standard full app sandbox. Apps cannot access location without having the Location permission. There's no difference between how any permissions or access control work for sandboxed Google Playu and other apps. Unless you give them access to location, they don't have access to location. It's straightforward as it is for any apps. There's nothing new to learn about how the app sandbox and permission model works for these.

Many apps use the Google Play geolocation service rather than the Android OS geolocation service. We re-route them to our own implementation of the Google Play geolocation service based on the OS geolocation service by default. This is covered in our documentation. If you grant them access to Location, they function fine via using the OS GNSS implementation through GmsCompat. Our documentation provides instructions on how to use the Google Play geolocation service:

https://grapheneos.org/usage#sandboxed-google-play-configuration

I don't think we need to add anything to the documentation about these topics. We do our best to explain that these run in the full standard app sandbox and that there are no differences between them and other apps. It doesn't seem you've absorbed that fully and therefore you think there are special things about what the Google Play apps can access or do on GrapheneOS when that isn't the case.
